### ISSUE TITLE
When the text is too long, it messes up the styling and looks inconsistent

### ISSUE THREAD

**Issue by butugruv** [butugruv/Better_Hero_Webpart#3]
When the text is too long, it messes up the styling and looks inconsistent.

Need to truncate text with '...' to keep the cards looking consistent

**Comment by TropicY** [comment]
Added truncating logic to mod-1 branch. Title and text will truncate to 1 line based on text

![image](https://github.com/butugruv/Better_Hero_Webpart/assets/121268307/6ca56054-a3e8-4882-92ac-56223d6912a9)
